format = """
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$golang\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$cmd_duration\
\n$character"""

add_newline = false

[character]
# format = "?"

[cmd_duration]
min_time = 0
format = "[$duration]($style)"

[directory]
truncation_length = 10
truncate_to_repo = false
truncation_symbol = ".../"
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
disabled = true

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[package]
disabled = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'