git:
  pagers:
    - pager: "delta --dark --paging=never"
customCommands:
  - key: 'o'
    context: 'files'
    command: 'yazi {{.SelectedFile.Name | quote}}'
    description: 'Open in yazi'
    output: terminal
