[tools]
go = "latest"
node = "latest"
"npm:@openai/codex" = "latest"
"npm:pnpm" = "latest"
"npm:vercel" = "latest"
"npm:@googleworkspace/cli" = "latest"
terraform = "latest"
uv = "latest"
bun = "latest"
rust = "latest"
aws-cli = "latest"
bitwarden = "latest"
gcloud = "latest"
python = "3.12"
"npm:agent-browser" = "latest"
aube = "latest"
"npm:defuddle" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
